name: simplexmq_io
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  simplexmq:
    git:
      url: git://github.com/simplex-chat/simplex-chat
      path: packages/simplexmq
      ref: ep/smp-client

dependency_overrides:
  simplexmq:
    path: ../simplexmq

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
