name: simplexmq
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  asn1lib: ^1.0.2
  pointycastle: ^3.3.4
  ssh_key: ^0.7.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
