name: Reproduce latest release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # every day at 02:00 night

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release
        shell: bash
        run: |
          curl --proto '=https' \
               --tlsv1.2 \
               -sSf -L \
               'https://api.github.com/repos/simplex-chat/simplex-chat/releases/latest' \
               2>/dev/null | \
          grep -i "tag_name" | \
          awk -F \" '{print "TAG="$4}' >> $GITHUB_ENV

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache /opt/microsoft /opt/pipx /usr/local/julia* /usr/lib/jvm /usr/lib/google-cloud-sdk /usr/lib/llvm* /usr/lib/firefox /usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/gradle* /usr/lib/python* /usr/local/share/powershell /usr/local/share/chromium /usr/local/share/vcpkg

      - name: Execute reproduce script
        run: |
          ${GITHUB_WORKSPACE}/scripts/simplex-chat-reproduce-builds.sh "$TAG" || :

      - name: Check if build has been reproduced
        env:
          url: ${{ secrets.STATUS_SIMPLEX_WEBHOOK_URL }}
          user: ${{ secrets.STATUS_SIMPLEX_WEBHOOK_USER }}
          pass: ${{ secrets.STATUS_SIMPLEX_WEBHOOK_PASS }}
        run: |
          if [ -f "${GITHUB_WORKSPACE}/${TAG}-simplex-chat/_sha256sums" ]; then
            exit 0
          else
            curl --proto '=https' --tlsv1.2 -sSf \
              -u "${user}:${pass}" \
              -H 'Content-Type: application/json' \
              -d '{"title": "üëæ GitHub: Runner", "description": "‚õîÔ∏è '"$TAG"' did not reproduce."}' \
              "$url"
            exit 1
          fi
